name: ci

on: push

jobs:
  run_test_and_build_docs:
    runs-on: macos-latest
    steps:
      - name: setup zig master
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - name: Update Homebrew
        run: |
          brew update --preinstall
      # - name: Configure Homebrew cache
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/Library/Caches/Homebrew/
      #     key: brew-${{ hashFiles('.github/brew-formulae') }}
      #     restore-keys: brew-
      - name: Install Homebrew dependencies
        run: |
          brew install opencv
        env:
          # HOMEBREW_NO_AUTO_UPDATE: 1
          # HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache zig
        id: opencv-cache
        uses: actions/cache@v2
        with:
          path: ./zig-cache
          key: ${{ runner.os }}-zig-cache
      - name: test
        run: zig build test
      - name: build examples
        run: zig build examples
      - name: build docs
        if: github.ref == 'refs/heads/main'
        run: zig build docs
      - uses: actions/upload-pages-artifact@v1
        if: github.ref == 'refs/heads/main'
        with:
          path: docs
      - name: delete tmp files
        run: rm -rf ./zig-cache/tmp

  deploy:
    needs: run_test_and_build_docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
