name: ci

on:
  push:

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check *.zig src/**/*.zig

  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        id: docker_cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: create tag
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          SHA=${{ github.sha }}
          IMAGE_LATEST="$IMAGE:latest"
          IMAGE_SHA="$IMAGE:$SHA"
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
             TAGS="$IMAGE_SHA,$IMAGE_LATEST"
          else
             TAGS=$IMAGE_SHA
          fi

          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "IMAGE_LATEST=$IMAGE_LATEST" >> $GITHUB_ENV
          echo "IMAGE_SHA=$IMAGE_SHA" >> $GITHUB_ENV
          echo "TAGS=$TAGS" >> $GITHUB_ENV

          echo TAGS $TAGS
      - name: Login GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull the latest image
        if: steps.docker_cache.outputs.cache-hit != 'true'
        run: docker pull ${{ env.IMAGE_LATEST }} || true
      - uses: docker/build-push-action@v3
        id: build-image
        with:
          push: true
          tags: ${{ env.TAGS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  run_test_and_build_docs:
    runs-on: ubuntu-latest
    needs: build_docker_image
    container:
      image: ghcr.io/${{ github.repository }}:${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - run: git config --global --add safe.directory /__w/zigcv/zigcv
        shell: bash
      - name: setup zig master
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - name: save zig-cache
        id: docker_cache
        uses: actions/cache@v3
        with:
          path: ./zig-cache
          key: ${{ runner.os }}-zig-cache-${{ github.event.repository.updated_at }}
          restore-keys: |
            ${{ runner.os }}-zig-cache-
      - name: test
        run: zig build test
      - name: build examples
        run: zig build examples
      - name: build docs
        if: github.ref == 'refs/heads/main'
        run: zig build test -Ddocs=true
      - uses: actions/upload-pages-artifact@v1
        if: github.ref == 'refs/heads/main'
        with:
          path: docs

  deploy:
    needs: run_test_and_build_docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
